### ISSUE TITLE
zabbix 4.0 agent failing to start

### ISSUE THREAD

**Issue by linecolumn** [scoopex/zabbix-agent-extensions#17]
Hi --

When I place in /etc/zabbix//zabbix_agentd.d/userparameter_apache.conf:

UserParameter=apache.writer[*],/usr/bin/zabbix_check_apache-mod-status writer $1 2>/dev/null
UserParameter=apache.reader[*],/usr/bin/zabbix_check_apache-mod-status reader $1 2>/dev/null
UserParameter=apache.keepalive[*],/usr/bin/zabbix_check_apache-mod-status keepalive $1 2>/dev/null
UserParameter=apache.total[*],/usr/bin/zabbix_check_apache-mod-status total $1 2>/dev/null
UserParameter=apache.all[*],/usr/bin/zabbix_check_apache-mod-status all $1 2>/dev/null
UserParameter=apache.accesses[*],/usr/bin/zabbix_check_apache-mod-status accesses $1 2>/dev/null
UserParameter=apache.kbytes[*],/usr/bin/zabbix_check_apache-mod-status kbytes $1 2>/dev/null

Zabbix agent fails to start....

Can't see the reason why.

As soon as this file is removed from directory zabbix agent start without any issue.

Please kindly advise.

Thank you!

**Comment by linecolumn** [comment]
Oh, I get it know. It is automagically included from 

Include=/usr/share/zabbix-agent-extensions/include.d/

**Comment by scoopex** [comment]
Correct, the Postinstallation adds this to the zabbix-agent configuration.
