### ISSUE TITLE
Zabbix 3.0 (LTS) compatibility issue

### ISSUE THREAD

**Issue by DanAlexson90** [scoopex/zabbix-agent-extensions#19]
Trying to import Linux templates (both 3.2 and 3.4 house 3.4 template actually:

[https://github.com/scoopex/zabbix-agent-extensions/blob/master/zabbix_templates/3.2/custom-os-linux.xml](https://github.com/scoopex/zabbix-agent-extensions/blob/master/zabbix_templates/3.2/custom-os-linux.xml)
[https://github.com/scoopex/zabbix-agent-extensions/blob/master/zabbix_templates/3.2/custom-os-linux-hardware.xml](https://github.com/scoopex/zabbix-agent-extensions/blob/master/zabbix_templates/3.2/custom-os-linux-hardware.xml)

[https://github.com/scoopex/zabbix-agent-extensions/blob/master/zabbix_templates/3.4/custom-os-linux.xml](https://github.com/scoopex/zabbix-agent-extensions/blob/master/zabbix_templates/3.4/custom-os-linux.xml)
[https://github.com/scoopex/zabbix-agent-extensions/blob/master/zabbix_templates/3.4/custom-os-linux-hardware.xml](https://github.com/scoopex/zabbix-agent-extensions/blob/master/zabbix_templates/3.4/custom-os-linux-hardware.xml)
) raises a number of errors, including unexpected and missing tags.

![fireshot capture 2 - omon_ configuration import - http___192 168 8 9_zabbix_conf import php](https://user-images.githubusercontent.com/5084067/41926154-6003ff3a-7990-11e8-9068-e15c615f698a.png)

**Comment by scoopex** [comment]
I'm sorry - it seems that you are using zabbix 3.0. This release is not supported by the current templates.
Probably it is a good idea to think about a upgrade.

**Comment by DanAlexson90** [comment]
Zabbix 4.0 LTS will only be released in Q3, 2018

[https://www.zabbix.com/life_cycle_and_release_policy](https://www.zabbix.com/life_cycle_and_release_policy)

We can't yet upgrade to the next LTS release, which is important.
