### ISSUE TITLE
YAML "parser" is not working

### ISSUE THREAD

**Issue by bilbolodz** [scoopex/zabbix-agent-extensions#24]
Your "YAML parcel" from zabbix_check_puppetstate is NOT working for such puppet summay file (space replaced by _ because of github autoformat):

---
__version: 
____config: 
____puppet: "3.8.7"
__time: 
____last_run: 1548848434

any ideas how to fix it?

**Comment by bilbolodz** [comment]
I've managed to "cope with this" by modifying match strings to:
 "^[ ]{2}([^ ]+):"
"^[ ]{2}[ ]+([^ ]+): (.+)$"

but it VERY UGLY trick to match my puppet file NOT the general solution.

**Comment by scoopex** [comment]
Can you upload a complete yaml file? (You can probably add with the code formatting or by uploading a example file). Sorry for doing manual yaml parsing :-) I just wanted to prevent the usage of an additional dependency.

**Comment by bilbolodz** [comment]
Manual yaml parsing is VERY good idea. I've uploaded my to pastbin: https://pastebin.com/JmBNNVkN

**Comment by bilbolodz** [comment]
Any news?

**Comment by scoopex** [comment]
Does the file really contain leading space in any line?
Can you upload a complete file as a example?

Have you considered to update to a not that outdated release of puppet ? :-) 
(in know that this question is rhetoric :-))

Solution idea:
Calculate the number of leading spaces after tripe dash header and trim that number of spaces in every line. 
Probably you can submit a patch, i would probably accept it.

**Comment by bilbolodz** [comment]
File uploaded.
[last_run_summary.yaml.gz](https://github.com/scoopex/zabbix-agent-extensions/files/2844987/last_run_summary.yaml.gz)

I'm not in power to change anything in puppet.

**Comment by scoopex** [comment]
Ah, ok :-) The file is really that short - i had the impression that you shortened the file.
Welcome to the world of opensource, i implemented a workaround for free, for you and your pretty outdated puppet release :-)

https://github.com/scoopex/zabbix-agent-extensions/commit/40dd29c1cf2121d19d76ab3d6160e9b06c950f00

I set a new release tag, but unfortunately travisci seems to be broken :-)
