### ISSUE TITLE
Availabilty status not displayed

### ISSUE THREAD

**Issue by jota2016** [scoopex/zabbix-agent-extensions#26]
Hi,
I have this template and the extensions working, but there is an issue with the availability display icon at hosts view.
When the agent is active and working, the icon should be green. When activating the template Custom - OS - Linux, all seems to be working, but the icon shows greyed out.
Could it be a problem with color configuration of the template?
Thanks.
Jota.

**Comment by scoopex** [comment]
Hi @jota2016,
you request is a bit too unspecific. There isn't somthing like a color configuration in templates. 
Please add more detailed information to this issue which provide a good understanding about your problem.

**Comment by jota2016** [comment]
Hi @scoopex,
You're right, maybe there's a lack of detail in the information.
I'm using a fresh new installed Zabbix Server 3.4. On a trial basis, I have a CentOS 7.6 client with the Zabbix 3.4 agent.
If I use the included template to monitor Linux machines, in the Hosts section, when the configuration is correct, in the Availability section, I can see the agent status (ZBX) colored in green. If the integration is not correct or the agent does not respond correctly, that section is colored red.
When I use your custom-os-linux template, it doesn't show any color, whether the agent service is running on the host or not. Despite that, the monitoring seems to work correctly, but I can't see the agent status in the Zabbix GUI.
