### ISSUE TITLE
Query on elasticsearch userparameter 

### ISSUE THREAD

**Issue by himanshurajput32** [scoopex/zabbix-agent-extensions#30]
Hi,
I'm new to zabbix. I was trying to understand the userparameter for elasticsearch defined here at 
https://github.com/scoopex/zabbix-agent-extensions/blob/master/extension-files/agent-config/zabbix_elasticsearch.conf

From where are we passing these args to script 
UserParameter=elasticsearch[*],/usr/bin/zabbix_check_elasticsearch $1 $2
These args are being passed through this elasticsearch[*] key but where are we providing the values.
Please help me to understand these $1 and $2. 
@scoopex

**Comment by scoopex** [comment]
Have a look at https://github.com/scoopex/zabbix-agent-extensions/blob/master/zabbix_templates/3.4/custom-service-elasticsearch-cluster.xml and https://github.com/scoopex/zabbix-agent-extensions/blob/master/zabbix_templates/3.4/custom-service-elasticsearch-node.xml.

Apply the template or review it with a editor and you will have many examples how to use this user parameter.
