### ISSUE TITLE
Please clarify installation from rpm/deb package

### ISSUE THREAD

**Issue by alexishughes** [scoopex/zabbix-agent-extensions#32]
Hi. I am new to zabbix and this module (about 1 hour) but quite good general linux maintenance.

I successfully installed zabbix server on my webserver. 

1) Must I also create localhost as an "agent" machine on zabbix server?
2) I executed:
yum localinstall zabbix-agent-extensions-2.4.36-1.noarch.rpm
which packages should I then install/enable/start?
3) When importing a template what would be standard option for a agent/server on the same single machine i.e. do not create new host etc.?

**Comment by scoopex** [comment]
From my point of view the documentation should be now better :-)
