### ISSUE TITLE
Problem to add custom-service-varnish.xml on Zabbix-3.0

### ISSUE THREAD

**Issue by murtzsarialtun** [scoopex/zabbix-agent-extensions#7]
When i try to import template a get an error :
Details

Created: Application "Custom - Service - Varnish" on "Custom - Service - Varnish".
Created: Application "Custom - Service - Varnish Backend" on "Custom - Service - Varnish".
Created: Application "Custom - Service - Varnish Cache" on "Custom - Service - Varnish".
Created: Application "Custom - Service - Varnish Connections" on "Custom - Service - Varnish".
Created: Application "Custom - Service - Varnish ESI" on "Custom - Service - Varnish".
Created: Application "Custom - Service - Varnish Fetch" on "Custom - Service - Varnish".
Created: Application "Custom - Service - Varnish Sessions" on "Custom - Service - Varnish".
Created: Application "Custom - Service - Varnish Workers" on "Custom - Service - Varnish".
Cannot find value map "Host status" used for item "Varnish Loadbalancer Health Check" on "Custom - Service - Varnish".

**Comment by scoopex** [comment]
Should be fixed now :-) 

https://github.com/scoopex/zabbix-agent-extensions/commit/94aa684d585a9182e1f729b1010fbc400eef8c3d
